using System.Collections.Generic;

namespace HoloLens.Hardware.Api.Power.Config
{
    public class Group2
    {
        public string Alias { get; set; }
        public string FriendlyName { get; set; }
        public string GUID { get; set; }
        public string Hidden { get; set; }
        public CONSOLELOCK2 CONSOLELOCK { get; set; }
        public DEVICEIDLE2 DEVICEIDLE { get; set; }
        public PERSONALITY2 PERSONALITY { get; set; }
        public WIFIINSTANDBY2 WIFIINSTANDBY { get; set; }
        public List<Setting13> Settings { get; set; }
        public DISKBURSTIGNORE2 DISKBURSTIGNORE { get; set; }
        public DISKIDLE2 DISKIDLE { get; set; }
        public DISKMAXPOWER2 DISKMAXPOWER { get; set; }
        public ALLOWSTANDBY2 ALLOWSTANDBY { get; set; }
        public AWAYMODE2 AWAYMODE { get; set; }
        public HIBERNATEIDLE2 HIBERNATEIDLE { get; set; }
        public HYBRIDSLEEP2 HYBRIDSLEEP { get; set; }
        public RTCWAKE2 RTCWAKE { get; set; }
        public STANDBYIDLE2 STANDBYIDLE { get; set; }
        public SYSTEMREQUIRED2 SYSTEMREQUIRED { get; set; }
        public UNATTENDSLEEP2 UNATTENDSLEEP { get; set; }
        public COALTIME2 COALTIME { get; set; }
        public DEEPSLEEP2 DEEPSLEEP { get; set; }
        public EXECTIME2 EXECTIME { get; set; }
        public PROCIR2 PROCIR { get; set; }
        public MODE2 MODE { get; set; }
        public PERPROCLOAD2 PERPROCLOAD { get; set; }
        public UNPARKTIME2 UNPARKTIME { get; set; }
        public LIDACTION2 LIDACTION { get; set; }
        public PBUTTONACTION2 PBUTTONACTION { get; set; }
        public SBUTTONACTION2 SBUTTONACTION { get; set; }
        public SHUTDOWN2 SHUTDOWN { get; set; }
        public UIBUTTONACTION2 UIBUTTON_ACTION { get; set; }
        public ASPM2 ASPM { get; set; }
        public CPCONCURRENCY2 CPCONCURRENCY { get; set; }
        public CPDECREASEPOL2 CPDECREASEPOL { get; set; }
        public CPDECREASETIME2 CPDECREASETIME { get; set; }
        public CPDISTRIBUTION2 CPDISTRIBUTION { get; set; }
        public CPHEADROOM2 CPHEADROOM { get; set; }
        public CPINCREASEPOL2 CPINCREASEPOL { get; set; }
        public CPINCREASETIME2 CPINCREASETIME { get; set; }
        public CPMAXCORES2 CPMAXCORES { get; set; }
        public CPMAXCORES12 CPMAXCORES1 { get; set; }
        public CPMINCORES2 CPMINCORES { get; set; }
        public CPMINCORES12 CPMINCORES1 { get; set; }
        public CPOVERUTIL2 CPOVERUTIL { get; set; }
        public CPPERF2 CPPERF { get; set; }
        public CPPERF12 CPPERF1 { get; set; }
        public DISTRIBUTEUTIL2 DISTRIBUTEUTIL { get; set; }
        public HETEROCLASS0FLOORPERF2 HETEROCLASS0FLOORPERF { get; set; }
        public HETEROCLASS1INITIALPERF2 HETEROCLASS1INITIALPERF { get; set; }
        public HETERODECREASETHRESHOLD2 HETERODECREASETHRESHOLD { get; set; }
        public HETERODECREASETIME2 HETERODECREASETIME { get; set; }
        public HETEROINCREASETHRESHOLD2 HETEROINCREASETHRESHOLD { get; set; }
        public HETEROINCREASETIME2 HETEROINCREASETIME { get; set; }
        public HETEROPOLICY2 HETEROPOLICY { get; set; }
        public IDLECHECK2 IDLECHECK { get; set; }
        public IDLEDEMOTE2 IDLEDEMOTE { get; set; }
        public IDLEDISABLE2 IDLEDISABLE { get; set; }
        public IDLEPROMOTE2 IDLEPROMOTE { get; set; }
        public IDLESCALING2 IDLESCALING { get; set; }
        public IDLESTATEMAX2 IDLESTATEMAX { get; set; }
        public LATENCYHINTPERF2 LATENCYHINTPERF { get; set; }
        public LATENCYHINTPERF12 LATENCYHINTPERF1 { get; set; }
        public LATENCYHINTUNPARK2 LATENCYHINTUNPARK { get; set; }
        public LATENCYHINTUNPARK12 LATENCYHINTUNPARK1 { get; set; }
        public PERFAUTONOMOUS2 PERFAUTONOMOUS { get; set; }
        public PERFAUTONOMOUSWINDOW2 PERFAUTONOMOUSWINDOW { get; set; }
        public PERFBOOSTMODE2 PERFBOOSTMODE { get; set; }
        public PERFBOOSTPOL2 PERFBOOSTPOL { get; set; }
        public PERFCHECK2 PERFCHECK { get; set; }
        public PERFDECPOL2 PERFDECPOL { get; set; }
        public PERFDECPOL12 PERFDECPOL1 { get; set; }
        public PERFDECTHRESHOLD2 PERFDECTHRESHOLD { get; set; }
        public PERFDECTHRESHOLD12 PERFDECTHRESHOLD1 { get; set; }
        public PERFDECTIME2 PERFDECTIME { get; set; }
        public PERFDECTIME12 PERFDECTIME1 { get; set; }
        public PERFDUTYCYCLING2 PERFDUTYCYCLING { get; set; }
        public PERFEPP2 PERFEPP { get; set; }
        public PERFHISTORY2 PERFHISTORY { get; set; }
        public PERFHISTORY12 PERFHISTORY1 { get; set; }
        public PERFINCPOL2 PERFINCPOL { get; set; }
        public PERFINCPOL12 PERFINCPOL1 { get; set; }
        public PERFINCTHRESHOLD2 PERFINCTHRESHOLD { get; set; }
        public PERFINCTHRESHOLD12 PERFINCTHRESHOLD1 { get; set; }
        public PERFINCTIME2 PERFINCTIME { get; set; }
        public PERFINCTIME12 PERFINCTIME1 { get; set; }
        public PROCTHROTTLEMAX2 PROCTHROTTLEMAX { get; set; }
        public PROCTHROTTLEMAX12 PROCTHROTTLEMAX1 { get; set; }
        public PROCTHROTTLEMIN2 PROCTHROTTLEMIN { get; set; }
        public PROCTHROTTLEMIN12 PROCTHROTTLEMIN1 { get; set; }
        public SYSCOOLPOL2 SYSCOOLPOL { get; set; }
        public THROTTLING2 THROTTLING { get; set; }
        public ADAPTBRIGHT2 ADAPTBRIGHT { get; set; }
        public ALLOWDISPLAY2 ALLOWDISPLAY { get; set; }
        public VIDEOADAPT2 VIDEOADAPT { get; set; }
        public VIDEOADAPTINC2 VIDEOADAPTINC { get; set; }
        public VIDEOANNOY2 VIDEOANNOY { get; set; }
        public VIDEOCONLOCK2 VIDEOCONLOCK { get; set; }
        public VIDEODIM2 VIDEODIM { get; set; }
        public VIDEOIDLE2 VIDEOIDLE { get; set; }
        public NSENINPUTPRETIME2 NSENINPUTPRETIME { get; set; }
        public USERPRESENCEPREDICTION2 USERPRESENCEPREDICTION { get; set; }
        public ESBATTTHRESHOLD2 ESBATTTHRESHOLD { get; set; }
        public ESBRIGHTNESS2 ESBRIGHTNESS { get; set; }
        public BATACTIONCRIT2 BATACTIONCRIT { get; set; }
        public BATACTIONLOW2 BATACTIONLOW { get; set; }
        public BATFLAGSLOW2 BATFLAGSLOW { get; set; }
        public BatteryLevel BATLEVELCRIT { get; set; }
        public BatteryLevel BATLEVELLOW { get; set; }
    }
}
